// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiMUl-URD-pzHtjavAz2PkFugolYR_aFQ',
    appId: '1:653211714389:android:10d741d560080c84d165dc',
    messagingSenderId: '653211714389',
    projectId: 'gtd-manager-f0d26',
    storageBucket: 'gtd-manager-f0d26.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXsapDs60MjIYsfGup_kvWln8Hi8nfszY',
    appId: '1:653211714389:ios:1d1f8721e576c511d165dc',
    messagingSenderId: '653211714389',
    projectId: 'gtd-manager-f0d26',
    storageBucket: 'gtd-manager-f0d26.firebasestorage.app',
    iosBundleId: 'com.example.gtdManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXsapDs60MjIYsfGup_kvWln8Hi8nfszY',
    appId: '1:653211714389:ios:1d1f8721e576c511d165dc',
    messagingSenderId: '653211714389',
    projectId: 'gtd-manager-f0d26',
    storageBucket: 'gtd-manager-f0d26.firebasestorage.app',
    iosBundleId: 'com.example.gtdManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBy5wCsX7IX3Atwqr_U6-kEnfGlnH4Q_0E',
    appId: '1:653211714389:web:d431cce1f3e13feed165dc',
    messagingSenderId: '653211714389',
    projectId: 'gtd-manager-f0d26',
    authDomain: 'gtd-manager-f0d26.firebaseapp.com',
    storageBucket: 'gtd-manager-f0d26.firebasestorage.app',
    measurementId: 'G-QW0CKZ3KE2',
  );

}